name: Android CI

on:
  push:
    branches:
      - 'development'
  pull_request:
    branches:
      - '*'
      - 'development'
      - '!release*'
      
      
  # Allow the actions to run manually from the actions tab. 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
   
      - name: codecov-umbrella 
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          
      - name: Grant execute permission for gradlew
        run: bash chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
